version: "2.4"

services:
  dexportalapi:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: dex-portal-api
    ports:
      - 8080:8080
    env_file:
      - ./api/.env
