version: "2.4"

services:
  dexportalapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dex-portal-api
    ports:
      - 4280:4280
    env_file:
      - ./api/.env  
    