version: "2.4"

services:
  dexportalapi:
    build:
      context: ./dex-portal-api
      dockerfile: Dockerfile
    container_name: dex-portal-api
    ports:
      - 8080:8080
    env_file:
      - ./dex-portal-api/.env
