FROM docker.io/library/gradle:jdk21 AS build
COPY ./ /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle buildFatJar --no-daemon

FROM docker.io/library/openjdk:23-jdk-oraclelinux9
RUN useradd -r app

# Trust CDC certificate bundle:
ADD bundle-ca.pem /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust

RUN mkdir /app && chown app:app /app
WORKDIR /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/dex-portal-api.jar
RUN chown app:app /app/dex-portal-api.jar

USER app
EXPOSE 8080:8080
ENTRYPOINT ["java","-jar","/app/dex-portal-api.jar"]
