name: "PR Checks - API Unit Tests"

on:
  pull_request:
    branches:
      - main
    paths:
      - api/**

defaults:
  run:
    working-directory: api

jobs:
  unit-test:
    name: "Run Gradle Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: 17
      - name: Unit Test
        run: ./gradlew test
