name: STG - Deploy Backend Release Canddiate

on:
    push:
      tags:
        - "*"

jobs:
    remote-trigger:
        uses: ./.github/workflows/remote-trigger-template.yml
        with:
          WORKFLOW: app-service-stg.yml
          REF: '${{ github.ref_name }}'  # Resolves to the tag that is pushed
        secrets: inherit
    
        