name: DEV - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/**

jobs:
  remote-trigger:
    uses: ./.github/workflows/remote-trigger-template.yml
    with:
      WORKFLOW: backend-dev.yml
    secrets: inherit
