name: "TST - Deploy Frontend"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy
        required: false
        default: main

jobs:
  deploy:
    name: "Deploy to tst"
    environment: tst
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install SWA CL
        run: yarn global add @azure/static-web-apps-cli
      - name: Install frontend dependencies
        run: yarn install
      - name: Generate build number
        id: gen_build_number
        run: |
          PACKAGE_VERSION=$(node -e "console.log(require(\"./package.json\").version)")
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "build_number=${PACKAGE_VERSION}_${SHORT_SHA}" >> $GITHUB_OUTPUT
      - name: Create tst environment variables
        run: |
          touch .env.tst
          echo VITE_SAMS_AUTHORITY_URL=https://apigw-stg.cdc.gov >> .env.tst
          echo VITE_SAMS_CLIENT_ID=${{ secrets.SAMS_CLIENT_ID }} >> .env.tst
          echo VITE_SAMS_AUTH_URL=https://apigw-stg.cdc.gov:8443/auth/oauth/v2/authorize >> .env.tst
          echo VITE_SAMS_USER_INFO_URL=https://apigw-stg.cdc.gov:8443/openid/connect/v1/userinfo >> .env.tst
          echo VITE_OAUTH_CALLBACK_URL=https://dextst.cdc.gov/oauth_callback >> .env.tst
          echo VITE_API_BASE_URL=https://ede-tst-portal-api.azurewebsites.net >> .env.tst
          echo VITE_APP_BUILD_NUMBER=${{ steps.gen_build_number.outputs.build_number }} >> .env.tst
          echo VITE_APP_CONFIG_CONNECTION_STRING="${{ secrets.APP_CONFIG_CONNECTION_STRING }}" >> .env.tst
          echo VITE_UPLOAD_API_ENDPOINT="${{ secrets.UPLOAD_API_ENDPOINT }}" >> .env.dev
      - name: Build frontend
        run: yarn build:tst
      - name: Deploy
        run: swa deploy ./dist -d ${{ secrets.AZURE_SWA_DEPLOY_TOKEN }} --env tst -w .
