name: "Deploy to Staging"

on:
  workflow_dispatch:
  pull_request: # TODO: Remove.  Only for testing.
  push:
    tags:
      - "**-rc"

jobs:
  create-rc:
    name: "Create Release Candidate"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install frontend dependencies
      run: yarn install
    - name: Install API dependencies
      working-directory: api
      run: npm install --production
    - name: Generate build number
      id: gen_build_number
      run: |
        NEXT_VERSION=${{github.ref_name}}
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "build_number=${NEXT_VERSION}_${SHORT_SHA}_rc" >> $GITHUB_OUTPUT
    - name: Create stg environment variables
      run: |
        touch .env.stg
        echo VITE_SAMS_AUTHORITY_URL=https://apigw-stg.cdc.gov >> .env.stg
        echo VITE_SAMS_CLIENT_ID=${{ secrets.SAMS_CLIENT_ID }} >> .env.stg
        echo VITE_SAMS_AUTH_URL=https://apigw-stg.cdc.gov:8443/auth/oauth/v2/authorize >> .env.stg
        echo VITE_SAMS_USER_INFO_URL=https://apigw-stg.cdc.gov:8443/openid/connect/v1/userinfo >> .env.stg
        echo VITE_OAUTH_CALLBACK_URL=https://dexstg.cdc.gov/oauth_callback >> .env.stg
        echo VITE_OAUTH_TOKEN_URL=https://dexstg.cdc.gov/api/token >> .env.stg
        echo VITE_APP_BUILD_NUMBER=${{ steps.gen_build_number.outputs.build_number }} >> .env.stg
    - name: Build frontend
      run: yarn build:dev
    - name: Build API
      working-directory: api
      run: npm run build
    - name: Create Github Prerelease
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: ${{ github.ref_name }}
        title: "Release Candidate ${{ github.ref_name }}"
        files: |
          dist
          api
