name: "Deploy to Dev"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to Dev"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install SWA CL
        run: yarn global add @azure/static-web-apps-cli
      - name: Install dependencies
        run: yarn install
      - name: Create dev environment variables
        run: |
          touch .env.dev
          echo VITE_SAMS_AUTHORITY_URL=https://apigw-stg.cdc.gov >> .env.dev
          echo VITE_SAMS_CLIENT_ID={{ secrets.SAMS_CLIENT_ID }} >> .env.dev
          echo VITE_SAMS_AUTH_URL=https://apigw-stg.cdc.gov:8443/auth/oauth/v2/authorize >> .env.dev
          echo VITE_SAMS_USER_INFO_URL=https://apigw-stg.cdc.gov:8443/openid/connect/v1/userinfo >> .env.dev
          echo VITE_OAUTH_CALLBACK_URL=https://dexdev.cdc.gov/oauth_callback >> .env.dev
          echo VITE_OAUTH_TOKEN_URL=https://dexdev.cdc.gov/api/token >> .env.dev
      - name: Build
        run: yarn build:dev
      - name: Deploy
        run: swa deploy ./dist --api-location ./api -d ${{ secrets.AZURE_SWA_DEPLOY_TOKEN }} --api-language node --api-version 18 --env dev -w .
