name: PR Check - Code Format

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**

jobs:
  unit-test:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: yarn
      - name: Prettier
        run: yarn format:check
