name: DEV - Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy
        required: false
  push:
    branches:
      - main

env:
  ENVIRONMENT: dev

jobs:
  deploy:
    name: Deploy to dev
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install SWA CL
        run: yarn global add @azure/static-web-apps-cli
      - name: Install frontend dependencies
        run: yarn install
      - name: Generate build number
        id: gen_build_number
        run: |
          PACKAGE_VERSION=$(node -e "console.log(require(\"./package.json\").version)")
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "build_number=${PACKAGE_VERSION}_${SHORT_SHA}" >> $GITHUB_OUTPUT
      - name: Create dev environment variables
        run: |
          touch .env.${{ env.ENVIRONMENT }}
          echo VITE_SAMS_AUTHORITY_URL=https://apigw-stg.cdc.gov >> .env.${{ env.ENVIRONMENT }}
          echo VITE_SAMS_CLIENT_ID=${{ secrets.SAMS_CLIENT_ID }} >> .env.${{ env.ENVIRONMENT }}
          echo VITE_SAMS_AUTH_URL=https://apigw-stg.cdc.gov:8443/auth/oauth/v2/authorize >> .env.${{ env.ENVIRONMENT }}
          echo VITE_SAMS_USER_INFO_URL=https://apigw-stg.cdc.gov:8443/openid/connect/v1/userinfo >> .env.${{ env.ENVIRONMENT }}
          echo VITE_OAUTH_CALLBACK_URL=https://dex${{ env.ENVIRONMENT }}.cdc.gov/oauth_callback >> .env.${{ env.ENVIRONMENT }}
          echo VITE_API_BASE_URL=https://ede-${{ env.ENVIRONMENT }}-portal-api.azurewebsites.net >> .env.${{ env.ENVIRONMENT }}
          echo VITE_APP_BUILD_NUMBER=${{ steps.gen_build_number.outputs.build_number }} >> .env.${{ env.ENVIRONMENT }}
          echo VITE_DEV_MOCKING_ENABLED=true >> .env.${{ env.ENVIRONMENT }}
          echo VITE_APP_CONFIG_CONNECTION_STRING="${{ secrets.APP_CONFIG_CONNECTION_STRING }}" >> .env.${{ env.ENVIRONMENT }}
          echo VITE_UPLOAD_API_ENDPOINT="${{ secrets.UPLOAD_API_ENDPOINT }}" >> .env.${{ env.ENVIRONMENT }}
      - name: Build frontend
        run: yarn build:${{ env.ENVIRONMENT }}
      - name: Deploy
        run: swa deploy ./dist -d ${{ secrets.AZURE_SWA_DEPLOY_TOKEN }} --env ${{ env.ENVIRONMENT }} -w .
  e2e:
    needs: deploy
    name: Run e2e regression tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          PLAYWRIGHT_TEST_BASE_URL: https://dex${{ env.ENVIRONMENT }}.cdc.gov
          SAMS_USERNAME: ${{ secrets.SAMS_USERNAME }}
          SAMS_PASSWORD: ${{ secrets.SAMS_PASSWORD }}
        run: npx playwright test
