name: STG - Deploy Frontend Release Candidate

on:
  push:
    tags:
      - "*"

env:
  ENVIRONMENT: stg

jobs:
  remote-trigger:
      uses: ./.github/workflows/remote-trigger-template.yml
      with:
        WORKFLOW: frontend-stg.yml
        REF: '${{ github.ref_name }}'  # Resolves to the tag that is pushed
      secrets: inherit
  
        